const majors = [
  { name: "Computer Science", acronym: "CS" },
  { name: "Information Technology", acronym: "IT" },
  { name: "Software Engineering", acronym: "SE" },
  { name: "Electrical Engineering", acronym: "EE" },
  { name: "Mechanical Engineering", acronym: "ME" },
  { name: "Civil Engineering", acronym: "CE" },
  { name: "Biomedical Engineering", acronym: "BME" },
  { name: "Aerospace Engineering", acronym: "AE" },
  { name: "Mathematics", acronym: "MATH" },
  { name: "Physics", acronym: "PHYS" },
  { name: "Chemistry", acronym: "CHEM" },
  { name: "Biology", acronym: "BIOL" },
  { name: "Data Science", acronym: "DS" },
  { name: "Artificial Intelligence", acronym: "AI" },
  { name: "Environmental Science", acronym: "ENSC" },
  { name: "Biotechnology", acronym: "BIOT" },
  { name: "Business Administration", acronym: "BUS" },
  { name: "Accounting", acronym: "ACCT" },
  { name: "Finance", acronym: "FIN" },
  { name: "Marketing", acronym: "MKTG" },
  { name: "Human Resource Management", acronym: "HRM" },
  { name: "Entrepreneurship", acronym: "ENTR" },
  { name: "International Business", acronym: "IB" },
  { name: "Supply Chain Management", acronym: "SCM" },
  { name: "English Literature", acronym: "ENGL" },
  { name: "History", acronym: "HIST" },
  { name: "Philosophy", acronym: "PHIL" },
  { name: "Art History", acronym: "ARTH" },
  { name: "Music", acronym: "MUS" },
  { name: "Theater and Drama", acronym: "THTR" },
  { name: "Creative Writing", acronym: "CW" },
  { name: "Psychology", acronym: "PSY" },
  { name: "Sociology", acronym: "SOC" },
  { name: "Political Science", acronym: "POLS" },
  { name: "Economics", acronym: "ECON" },
  { name: "Anthropology", acronym: "ANTH" },
  { name: "International Relations", acronym: "IR" },
  { name: "Medicine", acronym: "MED" },
  { name: "Nursing", acronym: "NS" },
  { name: "Pharmacy", acronym: "PHARM" },
  { name: "Public Health", acronym: "PH" },
  { name: "Dentistry", acronym: "DENT" },
  { name: "Physical Therapy", acronym: "PT" },
  { name: "Veterinary Medicine", acronym: "VMED" },
  { name: "Nutrition and Dietetics", acronym: "NUTR" },
  { name: "Graphic Design", acronym: "GD" },
  { name: "Fashion Design", acronym: "FD" },
  { name: "Industrial Design", acronym: "ID" },
  { name: "Interior Design", acronym: "INTD" },
  { name: "Film and Media Studies", acronym: "FMS" },
  { name: "Visual Arts", acronym: "VA" },
  { name: "Animation", acronym: "ANIM" },
  { name: "Law", acronym: "LAW" },
  { name: "Pre-Law", acronym: "PLAW" },
  { name: "Criminal Justice", acronym: "CJ" },
  { name: "Journalism", acronym: "JOUR" },
  { name: "Public Relations", acronym: "PR" },
  { name: "Media Studies", acronym: "MS" },
  { name: "Film Production", acronym: "FP" },
  { name: "Advertising", acronym: "ADV" },
  { name: "Environmental Studies", acronym: "ENS" },
  { name: "Urban Planning", acronym: "UP" },
  { name: "Gender Studies", acronym: "GS" },
  { name: "Cognitive Science", acronym: "COGS" },
  { name: "Neuroscience", acronym: "NEURO" },
  { name: "Cybersecurity", acronym: "CYB" },
  { name: "Renewable Energy", acronym: "RE" },
  { name: "Game Design", acronym: "GAME" },
];
export default majors;