const majors = [
  "Computer Science",
  "Information Technology",
  "Software Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Data Science",
  "Artificial Intelligence",
  "Environmental Science",
  "Biotechnology",
  "Business Administration",
  "Accounting",
  "Finance",
  "Marketing",
  "Human Resource Management",
  "Entrepreneurship",
  "International Business",
  "Supply Chain Management",
  "English Literature",
  "History",
  "Philosophy",
  "Art History",
  "Music",
  "Theater and Drama",
  "Creative Writing",
  "Psychology",
  "Sociology",
  "Political Science",
  "Economics",
  "Anthropology",
  "International Relations",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Dentistry",
  "Physical Therapy",
  "Veterinary Medicine",
  "Nutrition and Dietetics",
  "Graphic Design",
  "Fashion Design",
  "Industrial Design",
  "Interior Design",
  "Film and Media Studies",
  "Visual Arts",
  "Animation",
  "Law",
  "Pre-Law",
  "Criminal Justice",
  "Journalism",
  "Public Relations",
  "Media Studies",
  "Film Production",
  "Advertising",
  "Environmental Studies",
  "Urban Planning",
  "Gender Studies",
  "Cognitive Science",
  "Neuroscience",
  "Cybersecurity",
  "Renewable Energy",
  "Game Design",
];

export default majors;
